apiVersion: v1
kind: Service
metadata:
  name: pramoth-rtp-service
  namespace: pramoth1
spec:
  type: NodePort
  selector:
    app: pramoth-rtp
  ports:
   - nodePort:  30082
     port: 8000
     targetPort: 8000 

